management:
  health:
    livenessState.enabled: true
    readinessState.enabled: true
  endpoint.health.probes.enabled: true
  endpoints.web.exposure.include: "*"

spring:
  profiles:
    default: dev
  kafka:
    producer:
      group-id: spring-order-event-producer
      client-id: spring-order-controller
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
