management:
  health:
    livenessState.enabled: true
    readinessState.enabled: true
  endpoint.health.probes.enabled: true
  endpoints.web.exposure.include: "*"

spring:
  profiles:
    default: dev
  kafka:
    producer:
      group-id: spring-order-event
      client-id: spring-controller-service
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.demo.spring.controller.OrderSerializer
