apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-order-controller
  labels:
    app: spring-boot-order-controller
spec:
  replicas: 6
  selector:
    matchLabels:
      app: spring-boot-order-controller
  template:
    metadata:
      labels:
        app: spring-boot-order-controller
    spec:
      containers:
        - name: order-controller
          image: spring-boot/order-controller:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: spring-boot-order-controller-service
spec:
  selector:
    app: spring-boot-order-controller
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
