apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-order-service
  labels:
    app: spring-boot-order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-order-service
  template:
    metadata:
      labels:
        app: spring-boot-order-service
    spec:
      containers:
        - name: order-service
          image: spring-boot/order-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              port: 8080
              path: /actuator/health/readiness
            initialDelaySeconds: 1
            periodSeconds: 5
            failureThreshold: 2
          livenessProbe:
            httpGet:
              port: 8080
              path: /actuator/health/liveness
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              memory: 500Mi
              cpu: 100m
            limits:
              memory: 500Mi
              cpu: "2"

---

apiVersion: v1
kind: Service
metadata:
  name: spring-boot-order-service-service
spec:
  selector:
    app: spring-boot-order-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
