management:
  health:
    livenessState.enabled: true
    readinessState.enabled: true
  endpoint.health.probes.enabled: true
  endpoints.web.exposure.include: "*"

spring:
  profiles:
    default: dev
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: spring-order-event
      client-id: spring-demo-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.demo.spring.service.NewOrderEventDeserializer